# Generated by Django 4.2.5 on 2024-10-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'من نحن',
                'verbose_name_plural': 'من نحن',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=555)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'المجتمع',
                'verbose_name_plural': 'المجتمع',
            },
        ),
        migrations.CreateModel(
            name='communityService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/img')),
            ],
            options={
                'verbose_name': 'خدمة المجتمع',
                'verbose_name_plural': 'خدمة المجتمع',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=555)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'العملاء',
                'verbose_name_plural': 'العملاء',
            },
        ),
        migrations.CreateModel(
            name='downloadApp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='static/img')),
                ('image_android_app', models.ImageField(upload_to='static/img')),
                ('image_apple_app', models.ImageField(upload_to='static/img')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'حمل التطبيق',
                'verbose_name_plural': 'حمل التطبيق',
            },
        ),
        migrations.CreateModel(
            name='globalQuality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_cirtificate_1', models.ImageField(upload_to='static/img')),
                ('image_cirtificate_2', models.ImageField(upload_to='static/img')),
                ('image_cover', models.ImageField(upload_to='static/img')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'الجودة العالمية',
                'verbose_name_plural': 'الجودة العالمية',
            },
        ),
        migrations.CreateModel(
            name='Hasad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=555)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'حصاد',
                'verbose_name_plural': 'برنامج حصاد',
            },
        ),
        migrations.CreateModel(
            name='lastOffers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('video_url', models.FileField(upload_to='static/vid')),
            ],
            options={
                'verbose_name': 'آخر عرض',
                'verbose_name_plural': 'آخر العروض',
            },
        ),
        migrations.CreateModel(
            name='locationBranch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch', models.CharField(default='الفرع الرئيسي', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('date', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'مواقع الفروع',
                'verbose_name_plural': 'مواقع الفروع',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=555)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'منسوبينا',
                'verbose_name_plural': 'منسوبينا',
            },
        ),
        migrations.CreateModel(
            name='mustKnow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_url', models.FileField(upload_to='static/vid')),
            ],
            options={
                'verbose_name': 'من حقك تعرف',
                'verbose_name_plural': 'من حقك تعرف',
            },
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'اخبار المطعم',
                'verbose_name_plural': 'اخبار المطعم',
            },
        ),
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', models.CharField(default='percent', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.CharField(default='صالح حتى 30 سبتمبر', max_length=100)),
            ],
            options={
                'verbose_name': 'عروض خاصة',
                'verbose_name_plural': 'عروض خاصة',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(default='100', max_length=255)),
                ('number', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'خدماتنا',
                'verbose_name_plural': 'خدماتنا',
            },
        ),
        migrations.CreateModel(
            name='slide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.ImageField(upload_to='static/img')),
                ('name_page', models.IntegerField(choices=[(1, 'الصفحة الرئيسية'), (2, 'المجتمع'), (3, 'العملاء'), (4, 'منسوبينا'), (5, 'خدماتنا'), (6, 'برنامج حصاد'), (7, 'مواقع الفروع'), (8, 'جديدنا'), (9, 'من نحن')], default=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'السلايد',
                'verbose_name_plural': 'السلايدات',
            },
        ),
        migrations.CreateModel(
            name='TitleForPageChoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('name_page', models.IntegerField(choices=[(1, 'المجتمع'), (2, 'العملاء'), (3, 'منسوبينا'), (4, 'خدماتنا'), (5, 'برنامج حصاد'), (6, 'من نحن'), (7, 'كيف تبي طلبك'), (8, 'من حقك تعرف ')], default=1)),
            ],
            options={
                'verbose_name': 'عنوان الصفحة',
                'verbose_name_plural': 'عناوين الصفحات',
            },
        ),
        migrations.CreateModel(
            name='YourOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='static/img')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'كيف تبي طلبك',
                'verbose_name_plural': 'كيف تبي طلبك',
            },
        ),
    ]
