# Generated by Django 4.2.5 on 2024-10-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romanceHome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityservice',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='downloadapp',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='downloadapp',
            name='image_android_app',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='downloadapp',
            name='image_apple_app',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='globalquality',
            name='image_cirtificate_1',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='globalquality',
            name='image_cirtificate_2',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='globalquality',
            name='image_cover',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='lastoffers',
            name='video_url',
            field=models.FileField(upload_to='vid'),
        ),
        migrations.AlterField(
            model_name='mustknow',
            name='video_url',
            field=models.FileField(upload_to='vid'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image_url',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='yourorder',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
