# Generated by Django 4.2.16 on 2024-10-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romanceHome', '0002_alter_communityservice_image_alter_downloadapp_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
