# Generated by Django 4.2.16 on 2024-10-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romanceHome', '0003_alter_slide_description_alter_slide_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(default='', upload_to='img'),
            preserve_default=False,
        ),
    ]
