# Generated by Django 4.1.7 on 2023-07-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='static/img')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('description2', models.TextField()),
                ('title_ar', models.CharField(default='خدمات', max_length=255)),
                ('description_ar', models.TextField(default='تفاصيل الخدمات')),
                ('description2_ar', models.TextField(default='تفاصيل الخدمات 2')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='static/img')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('title_ar', models.CharField(default='خدمات', max_length=255)),
                ('description_ar', models.TextField(default='تفاصيل الخدمات')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='static/img')),
                ('title', models.CharField(max_length=255)),
                ('description', models.PositiveIntegerField()),
                ('title_ar', models.CharField(default='خدمات', max_length=255)),
                ('description_ar', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('student_count', models.PositiveIntegerField()),
                ('hours', models.TimeField()),
                ('teacher', models.CharField(max_length=255)),
                ('teacher_ar', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.ImageField(upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='opnion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='static/img')),
                ('title', models.CharField(max_length=255)),
                ('little_description', models.CharField(max_length=100)),
                ('big_description', models.TextField()),
                ('title_ar', models.CharField(default='خدمات', max_length=255)),
                ('little_description_ar', models.CharField(default='تفاصيل الخدمات', max_length=100)),
                ('big_description_ar', models.TextField(default='تفاصيل الخدمات')),
            ],
        ),
        migrations.CreateModel(
            name='partners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='static/img')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('title_ar', models.CharField(default='خدمات', max_length=255)),
                ('description_ar', models.TextField(default='الوزارة')),
                ('instagram_link', models.URLField(blank=True)),
                ('facebook_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='slide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.ImageField(upload_to='static/img')),
                ('title', models.CharField(max_length=255)),
                ('title_ar', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(default='تفاصيل الخدمات')),
            ],
        ),
        migrations.CreateModel(
            name='values',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('title_ar', models.CharField(default='خدمات', max_length=255)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(default='تفاصيل الخدمات')),
            ],
        ),
    ]
