# Generated by Django 4.1.7 on 2023-07-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilearnsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutskills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_title', models.CharField(max_length=255)),
                ('skill_title_ar', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_cover_page', models.ImageField(upload_to='static/img')),
                ('office', models.CharField(max_length=255)),
                ('office_ar', models.CharField(default='نهاية شارع الجزائر جوار محطة صافر – صنعاء', max_length=255)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(default='iLearn.ye@gmail.com', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image_cover_page',
            field=models.ImageField(default=1, upload_to='static/img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='image_cover_page',
            field=models.ImageField(default=1, upload_to='static/img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opnion',
            name='image_cover_page',
            field=models.ImageField(default=1, upload_to='static/img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partners',
            name='image_cover_page',
            field=models.ImageField(default=1, upload_to='static/img'),
            preserve_default=False,
        ),
    ]
