# Generated by Django 4.1.7 on 2023-08-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilearnsite', '0005_alter_aboutskills_options_alter_aboutus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutskills',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_ar',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='opnion',
            name='little_description_ar',
            field=models.CharField(default='تفاصيل الخدمات', max_length=1000),
        ),
    ]
