# Generated by Django 4.1.7 on 2023-08-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilearnsite', '0006_alter_aboutskills_options_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_more',
            field=models.ImageField(default=1, upload_to='static/img'),
            preserve_default=False,
        ),
    ]
