# Generated by Django 4.1.7 on 2023-08-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilearnsite', '0007_category_image_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image_more',
            new_name='image_more_ar',
        ),
        migrations.AddField(
            model_name='category',
            name='image_more_en',
            field=models.ImageField(default=1, upload_to='static/img'),
            preserve_default=False,
        ),
    ]
