# Generated by Django 4.1.7 on 2023-08-22 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilearnsite', '0008_rename_image_more_category_image_more_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partners',
            name='description',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='twitter_link',
        ),
    ]
