# Generated by Django 4.1.7 on 2023-08-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilearnsite', '0009_remove_partners_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image_cover_page',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
