# Generated by Django 4.1.7 on 2023-08-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilearnsite', '0010_alter_contact_image_cover_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image_cover_page',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image_cover_page',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='opnion',
            name='image_cover_page',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='image_cover_page',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
