# Generated by Django 4.0.4 on 2024-08-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilearnsite', '0011_alter_aboutus_image_cover_page_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gallery',
            new_name='YourOrder',
        ),
        migrations.AlterModelOptions(
            name='yourorder',
            options={'verbose_name': 'YourOrder', 'verbose_name_plural': 'YourOrders'},
        ),
    ]
