# Generated by Django 4.0.4 on 2024-08-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilearnsite', '0012_rename_gallery_yourorder_alter_yourorder_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_cover_page', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('office', models.CharField(max_length=255)),
                ('office_ar', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(default='iLearn.ye@gmail.com', max_length=100)),
            ],
            options={
                'verbose_name': 'offers',
                'verbose_name_plural': 'offers',
            },
        ),
        migrations.CreateModel(
            name='Hasad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_cover_page', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('office', models.CharField(max_length=255)),
                ('office_ar', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(default='iLearn.ye@gmail.com', max_length=100)),
            ],
            options={
                'verbose_name': 'Hasad',
                'verbose_name_plural': 'Hasad',
            },
        ),
        migrations.CreateModel(
            name='locationBranch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_cover_page', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('office', models.CharField(max_length=255)),
                ('office_ar', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(default='iLearn.ye@gmail.com', max_length=100)),
            ],
            options={
                'verbose_name': 'Hasad',
                'verbose_name_plural': 'Hasad',
            },
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_cover_page', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('office', models.CharField(max_length=255)),
                ('office_ar', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(default='iLearn.ye@gmail.com', max_length=100)),
            ],
            options={
                'verbose_name': 'offers',
                'verbose_name_plural': 'offers',
            },
        ),
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_cover_page', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('office', models.CharField(max_length=255)),
                ('office_ar', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(default='iLearn.ye@gmail.com', max_length=100)),
            ],
            options={
                'verbose_name': 'locationBranch',
                'verbose_name_plural': 'locationBranch',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_cover_page', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('office', models.CharField(max_length=255)),
                ('office_ar', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(default='iLearn.ye@gmail.com', max_length=100)),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.RenameModel(
            old_name='Course',
            new_name='Community',
        ),
        migrations.RenameModel(
            old_name='aboutskills',
            new_name='communityService',
        ),
        migrations.RenameModel(
            old_name='partners',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='category',
            new_name='downloadApp',
        ),
        migrations.RenameModel(
            old_name='aboutus',
            new_name='globalQuality',
        ),
        migrations.RenameModel(
            old_name='opnion',
            new_name='Members',
        ),
        migrations.RenameModel(
            old_name='values',
            new_name='mustKnow',
        ),
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': 'Community', 'verbose_name_plural': 'Communities'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customer'},
        ),
        migrations.AlterModelOptions(
            name='downloadapp',
            options={'verbose_name': 'downloadApp', 'verbose_name_plural': 'downloadApps'},
        ),
        migrations.AlterModelOptions(
            name='globalquality',
            options={'verbose_name': 'Global Quality', 'verbose_name_plural': 'Global Quality'},
        ),
        migrations.AlterModelOptions(
            name='mustknow',
            options={'verbose_name': 'mustKnow', 'verbose_name_plural': 'YourOrder'},
        ),
    ]
