# Generated by Django 4.0.4 on 2024-08-22 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilearnsite', '0013_about_hasad_locationbranch_news_offers_services_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityservice',
            options={'verbose_name': 'community Service', 'verbose_name_plural': 'community Service'},
        ),
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': 'Members', 'verbose_name_plural': 'Members'},
        ),
    ]
