# Generated by Django 4.0.4 on 2024-08-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilearnsite', '0014_alter_communityservice_options_alter_members_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='downloadapp',
            options={'verbose_name': 'download App', 'verbose_name_plural': 'download Apps'},
        ),
        migrations.AlterModelOptions(
            name='locationbranch',
            options={'verbose_name': 'locationBranch', 'verbose_name_plural': 'locationBranch'},
        ),
        migrations.AlterModelOptions(
            name='mustknow',
            options={'verbose_name': 'must Know', 'verbose_name_plural': 'must Know'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
        migrations.AlterModelOptions(
            name='offers',
            options={'verbose_name': 'offers', 'verbose_name_plural': 'offers'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Slide', 'verbose_name_plural': 'Slides'},
        ),
        migrations.AlterModelOptions(
            name='yourorder',
            options={'verbose_name': 'Your Order', 'verbose_name_plural': 'Your Orders'},
        ),
    ]
