# Generated by Django 4.0.4 on 2024-08-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilearnsite', '0015_alter_about_options_alter_downloadapp_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': 'Community', 'verbose_name_plural': 'Community'},
        ),
        migrations.AlterModelOptions(
            name='locationbranch',
            options={'verbose_name': 'location Branch', 'verbose_name_plural': 'location Branch'},
        ),
    ]
