# Generated by Django 4.0.4 on 2024-08-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilearnsite', '0016_alter_community_options_alter_locationbranch_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'من نحن', 'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': 'المجتمع', 'verbose_name_plural': 'Community'},
        ),
        migrations.AlterModelOptions(
            name='communityservice',
            options={'verbose_name': 'خدمة المجتمع', 'verbose_name_plural': 'community Service'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'العملاء', 'verbose_name_plural': 'Customer'},
        ),
        migrations.AlterModelOptions(
            name='downloadapp',
            options={'verbose_name': 'حمل التطبيق', 'verbose_name_plural': 'download Apps'},
        ),
        migrations.AlterModelOptions(
            name='globalquality',
            options={'verbose_name': 'الجودة العالمية', 'verbose_name_plural': 'Global Quality'},
        ),
        migrations.AlterModelOptions(
            name='hasad',
            options={'verbose_name': 'حصاد', 'verbose_name_plural': 'Hasad'},
        ),
        migrations.AlterModelOptions(
            name='locationbranch',
            options={'verbose_name': 'مواقع الفروع', 'verbose_name_plural': 'location Branch'},
        ),
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': 'منسوبينا', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='mustknow',
            options={'verbose_name': 'من حقك تعرف', 'verbose_name_plural': 'must Know'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'اخبار المطعم', 'verbose_name_plural': 'news'},
        ),
        migrations.AlterModelOptions(
            name='offers',
            options={'verbose_name': 'عروض خاصة', 'verbose_name_plural': 'offers'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'خدماتنا', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'السلايد', 'verbose_name_plural': 'Slides'},
        ),
        migrations.AlterModelOptions(
            name='yourorder',
            options={'verbose_name': 'كيف تبي طلبك', 'verbose_name_plural': 'Your Orders'},
        ),
        migrations.AddField(
            model_name='slide',
            name='name_page',
            field=models.IntegerField(choices=[(1, 'المجتمع'), (2, 'العملاء'), (3, 'منسوبينا'), (4, 'برنامج حصاد')], default=1),
        ),
    ]
