# Generated by Django 4.0.4 on 2024-08-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilearnsite', '0017_alter_about_options_alter_community_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleForPageChoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('name_page', models.IntegerField(choices=[(1, 'المجتمع'), (2, 'العملاء'), (3, 'منسوبينا'), (4, 'خدماتنا'), (5, 'برنامج حصاد'), (6, 'من نحن')], default=1)),
            ],
            options={
                'verbose_name': 'عنوان الصفحة',
                'verbose_name_plural': 'عناوين الصفحات',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'من نحن', 'verbose_name_plural': 'من نحن'},
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': 'المجتمع', 'verbose_name_plural': 'المجتمع'},
        ),
        migrations.AlterModelOptions(
            name='communityservice',
            options={'verbose_name': 'خدمة المجتمع', 'verbose_name_plural': 'خدمة المجتمع'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'العملاء', 'verbose_name_plural': 'العملاء'},
        ),
        migrations.AlterModelOptions(
            name='downloadapp',
            options={'verbose_name': 'حمل التطبيق', 'verbose_name_plural': 'حمل التطبيق'},
        ),
        migrations.AlterModelOptions(
            name='globalquality',
            options={'verbose_name': 'الجودة العالمية', 'verbose_name_plural': 'الجودة العالمية'},
        ),
        migrations.AlterModelOptions(
            name='hasad',
            options={'verbose_name': 'حصاد', 'verbose_name_plural': 'برنامج حصاد'},
        ),
        migrations.AlterModelOptions(
            name='locationbranch',
            options={'verbose_name': 'مواقع الفروع', 'verbose_name_plural': 'مواقع الفروع'},
        ),
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': 'منسوبينا', 'verbose_name_plural': 'منسوبينا'},
        ),
        migrations.AlterModelOptions(
            name='mustknow',
            options={'verbose_name': 'من حقك تعرف', 'verbose_name_plural': 'من حقك تعرف'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'اخبار المطعم', 'verbose_name_plural': 'اخبار المطعم'},
        ),
        migrations.AlterModelOptions(
            name='offers',
            options={'verbose_name': 'عروض خاصة', 'verbose_name_plural': 'عروض خاصة'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'خدماتنا', 'verbose_name_plural': 'خدماتنا'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'السلايد', 'verbose_name_plural': 'السلايدات'},
        ),
        migrations.AlterModelOptions(
            name='yourorder',
            options={'verbose_name': 'كيف تبي طلبك', 'verbose_name_plural': 'كيف تبي طلبك'},
        ),
        migrations.RenameField(
            model_name='about',
            old_name='office_ar',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='office',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='description',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='communityservice',
            old_name='skill_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='downloadapp',
            old_name='image_more_ar',
            new_name='image_android_app',
        ),
        migrations.RenameField(
            model_name='downloadapp',
            old_name='image_more_en',
            new_name='image_apple_app',
        ),
        migrations.RenameField(
            model_name='hasad',
            old_name='office',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='locationbranch',
            old_name='phone',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='locationbranch',
            old_name='office_ar',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='locationbranch',
            old_name='office',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='big_description',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='phone',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='office_ar',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='office',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='offers',
            old_name='email',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='offers',
            old_name='phone',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='offers',
            old_name='image_cover_page',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='offers',
            old_name='office',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='image_cover_page',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='phone',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='office_ar',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='office',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='email',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image_cover_page',
        ),
        migrations.RemoveField(
            model_name='about',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='community',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='community',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='community',
            name='image',
        ),
        migrations.RemoveField(
            model_name='community',
            name='image_cover_page',
        ),
        migrations.RemoveField(
            model_name='community',
            name='price',
        ),
        migrations.RemoveField(
            model_name='community',
            name='student_count',
        ),
        migrations.RemoveField(
            model_name='community',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='community',
            name='teacher_ar',
        ),
        migrations.RemoveField(
            model_name='community',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='communityservice',
            name='skill_title_ar',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='image_cover_page',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='downloadapp',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='downloadapp',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='hasad',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hasad',
            name='image_cover_page',
        ),
        migrations.RemoveField(
            model_name='hasad',
            name='office_ar',
        ),
        migrations.RemoveField(
            model_name='hasad',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='locationbranch',
            name='email',
        ),
        migrations.RemoveField(
            model_name='locationbranch',
            name='image_cover_page',
        ),
        migrations.RemoveField(
            model_name='members',
            name='big_description_ar',
        ),
        migrations.RemoveField(
            model_name='members',
            name='image',
        ),
        migrations.RemoveField(
            model_name='members',
            name='image_cover_page',
        ),
        migrations.RemoveField(
            model_name='members',
            name='little_description',
        ),
        migrations.RemoveField(
            model_name='members',
            name='little_description_ar',
        ),
        migrations.RemoveField(
            model_name='members',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='news',
            name='email',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_cover_page',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='office_ar',
        ),
        migrations.RemoveField(
            model_name='services',
            name='email',
        ),
        migrations.AddField(
            model_name='community',
            name='question',
            field=models.CharField(default='', max_length=555),
        ),
        migrations.AddField(
            model_name='communityservice',
            name='description',
            field=models.TextField(default=2024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communityservice',
            name='image',
            field=models.ImageField(default=1, upload_to='static/img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='answer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='question',
            field=models.CharField(default='', max_length=555),
        ),
        migrations.AddField(
            model_name='hasad',
            name='answer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hasad',
            name='question',
            field=models.CharField(default='', max_length=555),
        ),
        migrations.AddField(
            model_name='locationbranch',
            name='branch',
            field=models.CharField(default='فرع الرئيسي', max_length=100),
        ),
        migrations.AddField(
            model_name='locationbranch',
            name='url',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='question',
            field=models.CharField(default='', max_length=555),
        ),
        migrations.AddField(
            model_name='services',
            name='url',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slide',
            name='name_page',
            field=models.IntegerField(choices=[(1, 'الصفحة الرئيسية'), (2, 'المجتمع'), (3, 'العملاء'), (4, 'منسوبينا'), (5, 'خدماتنا'), (6, 'برنامج حصاد'), (7, 'مواقع الفروع'), (8, 'جديدنا'), (9, 'من نحن')], default=1),
        ),
    ]
