# Generated by Django 4.0.4 on 2024-08-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilearnsite', '0018_titleforpagechoice_alter_about_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalquality',
            old_name='image',
            new_name='image_cirtificate_1',
        ),
        migrations.RenameField(
            model_name='globalquality',
            old_name='image_ar',
            new_name='image_cirtificate_2',
        ),
        migrations.RenameField(
            model_name='globalquality',
            old_name='image_cover_page',
            new_name='image_cover',
        ),
        migrations.RenameField(
            model_name='globalquality',
            old_name='description2',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='globalquality',
            name='description2_ar',
        ),
        migrations.RemoveField(
            model_name='globalquality',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='globalquality',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='mustknow',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='mustknow',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='mustknow',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='title_ar',
        ),
        migrations.AddField(
            model_name='mustknow',
            name='video_url',
            field=models.ImageField(default=1, upload_to='static/img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yourorder',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yourorder',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
