# Generated by Django 4.0.4 on 2024-08-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilearnsite', '0019_rename_image_globalquality_image_cirtificate_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yourorder',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='yourorder',
            old_name='description',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='mustknow',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mustknow',
            name='title',
        ),
        migrations.RemoveField(
            model_name='yourorder',
            name='title',
        ),
        migrations.AlterField(
            model_name='titleforpagechoice',
            name='name_page',
            field=models.IntegerField(choices=[(1, 'المجتمع'), (2, 'العملاء'), (3, 'منسوبينا'), (4, 'خدماتنا'), (5, 'برنامج حصاد'), (6, 'من نحن'), (7, 'كيف تبي طلبك'), (8, 'من حقك تعرف ')], default=1),
        ),
    ]
