# Generated by Django 4.0.4 on 2024-09-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilearnsite', '0021_alter_globalquality_url_alter_locationbranch_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='lastOffers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BinaryField(default=False)),
                ('video_url', models.FileField(upload_to='static/img')),
            ],
            options={
                'verbose_name': 'آخر عرض',
                'verbose_name_plural': 'آخر العروض',
            },
        ),
    ]
