# Generated by Django 4.0.4 on 2024-09-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilearnsite', '0022_lastoffers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastoffers',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
