# Generated by Django 4.0.4 on 2024-09-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilearnsite', '0023_alter_lastoffers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastoffers',
            name='video_url',
            field=models.FileField(upload_to='static/vid'),
        ),
    ]
