# Generated by Django 4.0.4 on 2024-09-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilearnsite', '0024_alter_lastoffers_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mustknow',
            name='video_url',
            field=models.FileField(upload_to='static/vid'),
        ),
    ]
