# Generated by Django 4.0.4 on 2024-09-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilearnsite', '0025_alter_mustknow_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalquality',
            name='image_cover',
            field=models.ImageField(default=1, upload_to='static/img'),
            preserve_default=False,
        ),
    ]
