# Generated by Django 4.0.4 on 2024-09-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilearnsite', '0026_alter_globalquality_image_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='locationbranch',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='offers',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='titleforpagechoice',
            name='description',
            field=models.TextField(),
        ),
    ]
