# Generated by Django 4.0.4 on 2024-09-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilearnsite', '0027_alter_about_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='icon',
            field=models.CharField(default='fa-percent', max_length=255),
        ),
    ]
