# Generated by Django 4.0.4 on 2024-09-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilearnsite', '0028_alter_offers_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='question',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='customer',
            name='question',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='hasad',
            name='question',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='locationbranch',
            name='branch',
            field=models.CharField(default='الفرع الرئيسي', max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='question',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='offers',
            name='date',
            field=models.CharField(default='صالح حتى 30 سبتمبر', max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.CharField(default='100', max_length=255),
        ),
    ]
