# Generated by Django 4.0.4 on 2024-09-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilearnsite', '0029_alter_community_question_alter_customer_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='icon',
            field=models.CharField(default='percent', max_length=255),
        ),
    ]
